# ~/.kairnrc.tcl — kairn configuration
# Generated by: kairn --init-config
#
# Uncomment and modify settings as needed.
# See: https://github.com/rotmistrk/kairn/doc/config.md

# ── Editor settings ──────────────────────────────────────────────
# set kairn::keymap vi           ;# vi | emacs | classic
# set kairn::tab-width 4
# set kairn::line-numbers true
# set kairn::auto-save false
# set kairn::theme "gruvbox-dark"
# set kairn::shell ""            ;# empty = $SHELL
# set kairn::kiro-command "kiro-cli"

# ── Keybindings ──────────────────────────────────────────────────
# bind "ctrl+q"       { editor quit }
# bind "ctrl+s"       { buffer save }
# bind "ctrl+b"       { window toggle-tree }
# bind "ctrl+p"       { editor open-search }

# ── Theme ────────────────────────────────────────────────────────
# theme load "gruvbox-dark"
