#![deny(clippy::unwrap_used, clippy::expect_used)]

pub mod dialog;
pub mod event_loop;
pub mod file_list;
pub mod file_tree;
pub mod focus_group;
pub mod fuzzy_select;
pub mod input_line;
pub mod list_view;
pub mod menu;
pub mod notification;
pub mod overlay;
pub mod progress_bar;
pub mod scroll_view;
pub mod scrollbar;
pub mod split_pane;
pub mod status_bar;
pub mod tab_bar;
pub mod table;
pub mod text_area;
pub mod tree_view;
pub mod widget;

pub use dialog::{Dialog, DialogKind};
pub use event_loop::{EventLoop, LoopControl, Pollable, RunContext, TimerId};
pub use file_list::FileListData;
pub use file_tree::FileTreeData;
pub use focus_group::FocusGroup;
pub use fuzzy_select::FuzzySelect;
pub use input_line::{complete_from_history, CompletionFn, InputLine};
pub use list_view::{ListData, ListView};
pub use menu::{Menu, MenuItem};
pub use notification::Notification;
pub use overlay::{Anchor, Overlay};
pub use progress_bar::{ProgressBar, ProgressMode};
pub use scroll_view::ScrollView;
pub use scrollbar::Scrollbar;
pub use split_pane::{SplitDirection, SplitPane};
pub use status_bar::{StatusBar, StatusSpan};
pub use tab_bar::{TabBar, TabEntry};
pub use table::{Align, Column, Table};
pub use text_area::TextArea;
pub use tree_view::{TreeData, TreeView};
pub use widget::{EventResult, Widget, WidgetAction};
