//! Dispatch table part 2 (N-Z).

use crate::handler_exec::ExecEntry;

pub static TABLE_PART2: &[ExecEntry] = &[
    ExecEntry {
        names: &["add-root"],
        description: "Add directory as workspace root",
        requires_arg: true,
        handler: crate::handler_exec_misc::cmd_add_root,
    },
    ExecEntry {
        names: &["move-tab"],
        description: "Move tab to other subpanel",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_move_tab,
    },
    ExecEntry {
        names: &["new-dir"],
        description: "Create new directory",
        requires_arg: true,
        handler: crate::handler_dired::cmd_new_dir,
    },
    ExecEntry {
        names: &["new-file"],
        description: "Create new file",
        requires_arg: true,
        handler: crate::handler_dired::cmd_new_file,
    },
    ExecEntry {
        names: &["next-error"],
        description: "Jump to next error location",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_next_error,
    },
    ExecEntry {
        names: &["noblame"],
        description: "Hide git blame annotations",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_noblame,
    },
    ExecEntry {
        names: &["paste"],
        description: "Paste from clipboard",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_paste,
    },
    ExecEntry {
        names: &["prev-error"],
        description: "Jump to previous error location",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_prev_error,
    },
    ExecEntry {
        names: &["quit"],
        description: "Exit kairn",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_quit,
    },
    ExecEntry {
        names: &["remove-root"],
        description: "Remove workspace root",
        requires_arg: true,
        handler: crate::handler_exec_misc::cmd_remove_root,
    },
    ExecEntry {
        names: &["rename-file"],
        description: "Rename or move file",
        requires_arg: true,
        handler: crate::handler_dired::cmd_rename_file,
    },
    ExecEntry {
        names: &["run"],
        description: "Run project run command",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_run,
    },
    ExecEntry {
        names: &["save"],
        description: "Save current file",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_save,
    },
    ExecEntry {
        names: &["shell"],
        description: "Open new shell tab",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_shell,
    },
    ExecEntry {
        names: &["shrink"],
        description: "Decrease panel width",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_shrink,
    },
    ExecEntry {
        names: &["shrink-subpanel"],
        description: "Decrease subpanel size",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_shrink_subpanel,
    },
    ExecEntry {
        names: &["shrink-v"],
        description: "Decrease panel height",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_shrink_v,
    },
    ExecEntry {
        names: &["split"],
        description: "Split panel horizontally",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_split,
    },
    ExecEntry {
        names: &["structured", "struct", "tree"],
        description: "View file as structured tree (JSON)",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_structured,
    },
    ExecEntry {
        names: &["tab"],
        description: "View file as table (CSV/TSV)",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_tab,
    },
    ExecEntry {
        names: &["tab-next"],
        description: "Switch to next tab",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_tab_next,
    },
    ExecEntry {
        names: &["tab-prev"],
        description: "Switch to previous tab",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_tab_prev,
    },
    ExecEntry {
        names: &["tab-rename"],
        description: "Rename current tab",
        requires_arg: true,
        handler: crate::handler_exec_nav::cmd_tab_rename,
    },
    ExecEntry {
        names: &["test"],
        description: "Run project tests",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_test,
    },
    ExecEntry {
        names: &["test-at-cursor"],
        description: "Run test at cursor position",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_test_at_cursor,
    },
    ExecEntry {
        names: &["test-file"],
        description: "Run tests in current file",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_test_file,
    },
    ExecEntry {
        names: &["text"],
        description: "Switch to plain text view",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_text,
    },
    ExecEntry {
        names: &["theme"],
        description: "Change color theme (dark/light/auto)",
        requires_arg: false,
        handler: crate::handler_exec_misc::cmd_theme,
    },
    ExecEntry {
        names: &["toggle-tools"],
        description: "Show/hide tools panel",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_toggle_tools,
    },
    ExecEntry {
        names: &["toggle-tree"],
        description: "Show/hide tree panel",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_toggle_tree,
    },
    ExecEntry {
        names: &["vsplit"],
        description: "Split panel vertically",
        requires_arg: false,
        handler: crate::handler_exec_misc::cmd_vsplit,
    },
    ExecEntry {
        names: &["welcome"],
        description: "Show welcome screen",
        requires_arg: false,
        handler: crate::handler_exec_misc::cmd_welcome,
    },
    ExecEntry {
        names: &["zoom"],
        description: "Maximize/restore current panel",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_zoom,
    },
];
