//! Dispatch table part 1 (A-M).

use crate::handler_exec::ExecEntry;

pub static TABLE_PART1: &[ExecEntry] = &[
    ExecEntry {
        names: &["blame"],
        description: "Show git blame annotations",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_blame,
    },
    ExecEntry {
        names: &["build"],
        description: "Run project build command",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_build,
    },
    ExecEntry {
        names: &["clipboard"],
        description: "Show clipboard ring contents",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_clipboard,
    },
    ExecEntry {
        names: &["close"],
        description: "Close current tab",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_close,
    },
    ExecEntry {
        names: &["code-action"],
        description: "Show LSP code actions",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_code_action,
    },
    ExecEntry {
        names: &["copy-file"],
        description: "Copy file or directory",
        requires_arg: true,
        handler: crate::handler_dired::cmd_copy_file,
    },
    ExecEntry {
        names: &["cycle-subpanel"],
        description: "Move focus between subpanels",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_cycle_subpanel,
    },
    ExecEntry {
        names: &["delete-file"],
        description: "Delete file or directory",
        requires_arg: true,
        handler: crate::handler_dired::cmd_delete_file,
    },
    ExecEntry {
        names: &["diff"],
        description: "Show diff of current file vs git HEAD",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_diff,
    },
    ExecEntry {
        names: &["edit", "e"],
        description: "Open file for editing",
        requires_arg: true,
        handler: crate::handler_exec_edit::cmd_edit,
    },
    ExecEntry {
        names: &["focus-down"],
        description: "Move focus to panel below",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_focus_down,
    },
    ExecEntry {
        names: &["focus-left"],
        description: "Move focus to panel on left",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_focus_left,
    },
    ExecEntry {
        names: &["focus-right"],
        description: "Move focus to panel on right",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_focus_right,
    },
    ExecEntry {
        names: &["focus-up"],
        description: "Move focus to panel above",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_focus_up,
    },
    ExecEntry {
        names: &["fmt!"],
        description: "Format buffer with built-in formatter",
        requires_arg: false,
        handler: crate::handler_format_builtin::cmd_format_builtin,
    },
    ExecEntry {
        names: &["git-base"],
        description: "Set git diff base reference",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_git_base,
    },
    ExecEntry {
        names: &["git-commit"],
        description: "Commit staged changes",
        requires_arg: true,
        handler: crate::handler_exec_edit::cmd_git_commit,
    },
    ExecEntry {
        names: &["git-stage"],
        description: "Stage file for commit",
        requires_arg: true,
        handler: crate::handler_exec_edit::cmd_git_stage,
    },
    ExecEntry {
        names: &["git-unstage"],
        description: "Unstage file from commit",
        requires_arg: true,
        handler: crate::handler_exec_edit::cmd_git_unstage,
    },
    ExecEntry {
        names: &["git-untrack"],
        description: "Remove file from git tracking",
        requires_arg: true,
        handler: crate::handler_exec_edit::cmd_git_untrack,
    },
    ExecEntry {
        names: &["grep"],
        description: "Search project files for pattern",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_grep,
    },
    ExecEntry {
        names: &["grow"],
        description: "Increase panel width",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_grow,
    },
    ExecEntry {
        names: &["grow-subpanel"],
        description: "Increase subpanel size",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_grow_subpanel,
    },
    ExecEntry {
        names: &["grow-v"],
        description: "Increase panel height",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_grow_v,
    },
    ExecEntry {
        names: &["help"],
        description: "Show help (optional: topic name)",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_help,
    },
    ExecEntry {
        names: &["kiro"],
        description: "Start Kiro AI session",
        requires_arg: false,
        handler: crate::handler_kiro::cmd_kiro,
    },
    ExecEntry {
        names: &["layout"],
        description: "Cycle layout mode (auto/wide/tall)",
        requires_arg: false,
        handler: crate::handler_exec_nav::cmd_layout,
    },
    ExecEntry {
        names: &["log"],
        description: "Show git commit log",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_log,
    },
    ExecEntry {
        names: &["lsp"],
        description: "LSP control (start/stop/restart)",
        requires_arg: true,
        handler: crate::handler_exec_edit::cmd_lsp,
    },
    ExecEntry {
        names: &["lsp-rename"],
        description: "Rename symbol via LSP",
        requires_arg: true,
        handler: crate::handler_exec_edit::cmd_lsp_rename,
    },
    ExecEntry {
        names: &["lsp-status"],
        description: "Show LSP server status",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_lsp_status,
    },
    ExecEntry {
        names: &["messages"],
        description: "Show message log",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_messages,
    },
    ExecEntry {
        names: &["problems"],
        description: "Show diagnostics panel",
        requires_arg: false,
        handler: crate::handler_exec_edit::cmd_problems,
    },
    ExecEntry {
        names: &["replace", "sed"],
        description: "Search and replace in buffer",
        requires_arg: true,
        handler: crate::handler_exec_edit::cmd_replace,
    },
    ExecEntry {
        names: &["set", "setglobal"],
        description: "Set editor option",
        requires_arg: true,
        handler: crate::handler_exec_misc::cmd_set,
    },
];
